project:
  type: website
  output-dir: docs

author:
  - name: Vagish Hemmige
    affiliations:
      - Montefiore Medical Center/ Albert Einstein College of Medicine
    email: vahemmig@montefiore.org

website:
  site-url: https://vagishhemmige.github.io/Cryptococcus-donor-screening-CEA/
  repo-url: https://github.com/VagishHemmige/Cryptococcus-donor-screening-CEA
  repo-actions: [edit, issue]
  title: "Cryptococcus donor screening cost effectiveness analysis"
  
  

  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: quarto/base_case.html
        text: Base case analysis
      - href: quarto/additional_trees.html
        text: Additional tree analyses
      - href: quarto/tornado.html
        text: One-way sensitivity analysis (tornado plot)
      - href: quarto/psa.html
        text: Probabilistic sensitivity analyses
      - href: quarto/about.html
        text: About

  page-navigation: true


custom-callout:
  Rcode:
    icon: true
    icon-symbol: "💻 "
    color: "pink"

filters:
- custom-callout

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    page-layout: full
    code-summary: "Click to show/hide R Code"

